default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe-api
  username: test3
  password: test3
  host: localhost
  port: 5432

test:
  <<: *default
  database: recipe-api_name

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
